version: "3.8"
services:
  nginx:
    container_name: nginx_service
    env_file: cloudflare.env
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.nginx
    ports:
      - "80:8000"
      - "443:443"
    networks:
    - proxy
    - nextCloud_network
    - test_steelbooksatbestbuy_network
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.cloudflared
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
  nextCloud_network:
    driver: bridge
  test_steelbooksatbestbuy_network:
    driver: bridge
