version: "3.8"
services:
 monero_node:
   image: monero
   restart: unless-stopped
   ports:
     - 18081:18081
   container_name: monero_node
   logging:
     driver: "json-file"
     options:
       max-size: "200k"
       max-file: "10"
