services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    networks:
      - jenkins_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  jenkins_network:
    name: jenkins_network
    driver: bridge