version: "3.8"
services:
  nginx:
    container_name: nginx_service
    build:
      context: .
      dockerfile: Dockerfiles/Nginx.dockerfile
    ports:
      - "8080:8000"
      - "8443:443"
    networks:
    - proxy
    - nextCloud_network
    - test_steelbooksatbestbuy_network
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    env_file: cloudflare.env
    build:
      context: .
      dockerfile: Dockerfiles/Cloudflared.dockerfile
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
  nextCloud_network:
    driver: bridge
  test_steelbooksatbestbuy_network:
    driver: bridge
