version: "3.8"
services:
  nginx:
    container_name: nginx_service
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.nginx
    ports:
      - "80:8000"
      - "443:443"
    networks:
    - proxy
    - nextCloud_network
    - steelBooks_network
  cloudflared:
    image: cloudflare/cloudflared:2022.1.3-amd64 #update the verion where necessary
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - proxy
    command: tunnel --config /home/nonroot/.cloudflared/config.yml run UUID #Replace UUID with your actual UUID
    volumes:
      - /opt/cloudflared/data:/home/nonroot/.cloudflared/

networks:
  proxy:
    driver: bridge
    external: true
  nextCloud_network:
  test_steelbooksatbestbuy_network:
