version: "3.8"
services:
  nginx_app:
    container_name: nginx_service
    build:
      context: .
      dockerfile: Dockerfiles/Nginx.dockerfile
    networks:
    - proxy
    - nextcloud_network
    - steelbooksatbestbuy_network
  cloudflared:
    container_name: cloudflared
#    env_file: cloudflare_configs/cloudflare.env if the tunnel was setup via the UI
    build:
      context: .
      dockerfile: Dockerfiles/Cloudflared.dockerfile
    networks:
      - proxy


  nextcloud_postgres:
      image: postgres:alpine
      restart: unless-stopped
      volumes:
          - nextcloud_postgres_db:/var/lib/postgresql/data
      environment:
          - POSTGRES_PASSWORD=/run/secrets/postgres_db_password
          - POSTGRES_DB=nextcloud_postgres_db
          - POSTGRES_USER=nextcloud_postgres_db_admin
      container_name: nextcloud_postgres
      networks:
          - nextcloud_network
  nextcloud_app:
      image: nextcloud:apache
      restart: unless-stopped
      volumes:
          - nextcloud:/var/www/html
      environment:
          - POSTGRES_DB=nextcloud_postgres_db
          - POSTGRES_USER=nextcloud_postgres_db_admin
          - POSTGRES_PASSWORD=/run/secrets/postgres_db_password
          - POSTGRES_HOST=nextcloud_postgres
          - VIRTUAL_HOST=the_machine.jacemanshadi.ca
          - LETSENCRYPT_HOST=the_machine.jacemanshadi.ca
      depends_on:
          - nextcloud_postgres
      networks:
          - nextcloud_network
      container_name: nextcloud_app

volumes:
    nextcloud:
        name: nextcloud_volume
    nextcloud_postgres_db:
        name: nextcloud_postgres_db

networks:
  proxy:
    driver: bridge
    name: proxy
  nextcloud_network:
    name: nextcloud_network
    driver: bridge
  steelbooksatbestbuy_network:
    driver: bridge
    name: steelbooksatbestbuy_network
