version: "3.8"
services:
  nextcloud_postgres:
      image: postgres:alpine
      env_file:
          - nextcloud.env
      restart: unless-stopped
      volumes:
          - nextcloud_postgres_db:/var/lib/postgresql/data
      container_name: nextcloud_postgres
      networks:
          - nextcloud_network
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"

  nextcloud_redis:
    image: redis
    restart: unless-stopped
    container_name: nextcloud_redis
    networks:
      - nextcloud_network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


  nextcloud_app:
      image: nextcloud:27.0.1-apache
      env_file:
          - nextcloud.env
      restart: unless-stopped
      volumes:
          - nextcloud:/var/www/html
      environment:
          - POSTGRES_HOST=nextcloud_postgres
#      depends_on:
#          - nextcloud_postgres
      networks:
          - nextcloud_network
      ports:
          - 8888:80 #so the instance can be accessed without the use of cloudflare tunnel in the LAN
      container_name: nextcloud_app

volumes:
    nextcloud:
        name: nextcloud_volume
    nextcloud_postgres_db:
        name: nextcloud_postgres_db

networks:
  nextcloud_network:
    name: nextcloud_network
    driver: bridge