tunnel: 3b686b85-3e91-43c2-85c5-b2968992512c
credentials-file: /etc/cloudflared/credentials.json

ingress:
 - hostname: steelbooks.modernneo.com.getthemachine.net
   service: http://nginx_app:80
 - service: http_status:404
